### ISSUE TITLE
Cluster Error

### ISSUE THREAD

**Issue by ravilution** [wood1986/ln#6]
I got below error when I tried to log with cluster. I might be making some mistake. Can you please provide a sample example for logging with cluster/workers.
`
Error: ENOENT, open '../logs/error/log.1506011842'
    at Error (native)
events.js:85
      throw er; // Unhandled 'error' event
`

**Comment by wood1986** [comment]
1. Are you sure this is not a permission and folder existence issue?
2. if not, you can take look to https://github.com/wood1986/ln/blob/master/test/cluster.test.js

**Comment by wood1986** [comment]
Any updates?
If no, I will close it

**Comment by ravilution** [comment]
Sorry. Have not tried it yet. So busy. I will try it today and will keep
you posted. You can close it meanwhile. I will contact you via email. Thank
you. Highly appreciate.

- Ravi

**Comment by wood1986** [comment]
No problem

**Comment by ravilution** [comment]
I tried it. Works great. Sorry about the delay. Guess what? I am going to use this for a huge project. Thanks to you.
I got some quick question.

1. How can I remove n from getting logger. They are same values repeating and consuming space. I know I can use "formatter" but wont that slow down the logging?
2. What exactly is v in log

**Comment by wood1986** [comment]
1. I won't recommend removing `n` because this attribute gives you a scope for querying. For example if you use Splunk, you can select the log entries by using this attribute.
2. When the default json format is changed, you still can separate the new and old format by this attribute.

**Comment by ravilution** [comment]
Makes sense. Thanks again.
